{% set name = "mpipartition" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpipartition-{{ version }}.tar.gz
  sha256: c6e5be3be9fbebbad3aa1e6ae091017c9b11b6f5ede4b409ea0e8414287f390c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mpipartition-s2 = mpipartition.scripts.s2_prediction:cli

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - mpi4py
    - numpy
    - numba
    - click

test:
  commands:
    - pip check
    - mpirun -n 1 python -c "import mpipartition"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ArgonneCPAC/MPIPartition
  summary: MPI volume decomposition and particle distribution tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
