{% set name = "mpipartition" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpipartition-{{ version }}.tar.gz
  sha256: 583f26a79cb770b290f86ee5104ea008c9e81e0ea612868e814656b5be5f0c61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mpipartition-s2 = mpipartition.scripts.s2_prediction:cli

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - mpi4py
    - numpy
    - numba

test:
  commands:
    - pip check
    # I lifted these out of the mpi4py feedstock.
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - mpirun -n 1 python -c "import mpipartition"
  requires:
    - pip

about:
  home: https://github.com/ArgonneCPAC/MPIPartition
  summary: MPI volume decomposition and particle distribution tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
