{% set name = "mpipartition" %}
{% set version = "1.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpipartition-{{ version }}.tar.gz
  sha256: b5d8e1cfce04dc54e986dc04a8bed5319a69d2eeb26fabe1440089eabf29b0f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mpipartition-s2 = mpipartition.scripts.s2_prediction:cli

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - mpi4py >=3.1.6
    - numpy >1.2
    - numba >=0.57.0
    - click

test:
  commands:
    - pip check
    - mpirun -n 1 python -c "import mpipartition"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ArgonneCPAC/MPIPartition
  summary: MPI volume decomposition and particle distribution tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
