{% set name = "mpipartition" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpipartition-{{ version }}.tar.gz
  sha256: 58d46ff3b0c1ef4df275a3ace5901b80245b38cee8e41741ad3f434767f9525d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mpipartition-s2 = mpipartition.scripts.s2_prediction:cli

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - mpi4py
    - numpy
    - numba
    - click

test:
  commands:
    - pip check
    - mpirun -n 1 python -c "import mpipartition"
  requires:
    - pip

about:
  home: https://github.com/ArgonneCPAC/MPIPartition
  summary: MPI volume decomposition and particle distribution tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
